name: quados
description: QuadOS Image

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 39

modules:
  - type: files
    files:
      - usr: /usr # copies config/files/usr into your image's /usr.
                  # put configuration files you want in /etc/ on a booted system 
                  # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
    remove:
      firefox
      firefox-langpacks

  - type: default-flatpaks
    notify: true
    system:

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

