name: Live ISO
on:
  push:
    branches: main
  workflow_dispatch:
concurrency:
  cancel-in-progress: true
  group: "build"
jobs:
  build:
    name: Build Custom Image
    runs-on: ubuntu-latest
    container:
      image: debian:latest
      volumes:
        - /proc:/proc
      options: --privileged
    steps:
      - uses: actions/checkout@v4.1.2
      - name: Install packages
        run: |
          apt update
          apt install -y live-build
      - name: Build ISO
        run: "lb build"
      - name: Attach ISO
        uses: actions/upload-artifact@v4.3.1
        with:
          name: "quados.iso"
          path: "*.iso"
