name: Live ISO
on:
  push:
    branches: main
  workflow_dispatch:
jobs:
  build:
    name: Build Custom Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2
      - name: Install live-build
        run: "sudo apt-get install -y live-build"
      - name: Configure live-build
        run: "lb config --mirror-bootstrap http://deb.debian.org/debian --mirror-chroot-security http://deb.debian.org/debian-security --distribution sid --mode debian --archive-areas 'main contrib non-free'"
      - name: Build ISO
        run: "sudo lb build"
      - name: Attach ISO
        uses: actions/upload-artifact@v4.3.1
