name: Live ISO
on:
  push:
    branches: main
  workflow_dispatch:
concurrency:
  cancel-in-progress: true
  group: "build"
jobs:
  build:
    name: Build Custom Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2
      - name: Install packages
        run: "sudo apt-get install -y live-build"
      - name: Configure live-build
        run: "lb config --quiet --distribution bookworm --mode debian --mirror-bootstrap https://deb.debian.org/debian --mirror-chroot-security https://security.debian.org"
      - name: Build ISO
        run: "sudo lb build"
      - name: Attach ISO
        uses: actions/upload-artifact@v4.3.1
        with:
          name: "*.iso"
